#!/bin/sh
# 
# Bash Helpers
#

# source all '.al', used as plugin system for env
srcCustom() {
	mkdir -p ~/env/tmp
	for al in $(find ~/env -name '*.al'); do source $al; done
	for al in $(find ~/env/tmp/ -type f -name '*' ); do source $al ; done
}

# Exec
# activated on source call
srcCustom
