#!/bin/sh
# 
# Source all '.al', used as plugin system for env
#

for al in $(find ~/env -name '*.al'); do . $al; done

# Load Powerline shell ( if installed )
if [ "$(command -v powerline-shell)" ]; then
    function _update_ps1() {
        PS1=$(powerline-shell $?)
    }
    if [[ $TERM != linux && ! $PROMPT_COMMAND =~ _update_ps1 ]]; then
        PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
    fi
fi

# Load theFuck ( if installed )
if [ "$(command -v thefuck)" ]; then
    eval $(thefuck --alias)
fi

# Pull down latest env version
if [ -z $ENV_SKIP_GIT_PULL ]; then
    git -C ~/env pull origin master &> /dev/null
fi

# Load ssh keys
if [ -z $ENV_SKIP_SSH_ADD ] && [ `command -v ssh-agent` ]; then
    eval "$(ssh-agent -s)" >&/dev/null
    for key in $(grep -l "PRIVATE KEY" ~/.ssh/*); do
        ssh-add $key >&/dev/null;
    done
fi